### ISSUE TITLE
[BUG] nightly image creation fails with 'Checksum.hpp' file not found

### ISSUE THREAD

**Issue by fwc** [nebulastream/nebulastream#714]
### Version / Commit

d12ea49f8a3ce923aea674dbb311d5ef43fda50b, but I think it could be possible that the bug was introduced with 8801395196b9c107f94bc72ca7cd6cb39e167058.

### What happened?

The `create-nightly-image` step of the [last](https://github.com/nebulastream/nebulastream-public/actions/runs/13667391542) [two](https://github.com/nebulastream/nebulastream-public/actions/runs/13690058765) nightly runs failed.

Concretely, the build failed with the error:

```
/home/ubuntu/src/nes-plugins/Sinks/ChecksumSink/ChecksumSink.hpp:31:10: fatal error: 'Checksum.hpp' file not found
   31 | #include <Checksum.hpp>
      |          ^~~~~~~~~~~~~~
1 error generated.
```

AFAICS, this is caused by the following:

- the nightly image (and thus also `ChecksumSink.cpp`) builds without tests, i.e. with `-DNES_ENABLES_TESTS=0`
- `Checksum.hpp` being part of `systest`, and not being included/built since the [whole folder isn't included in cmake](https://github.com/nebulastream/nebulastream-public/blob/d12ea49f8a3ce923aea674dbb311d5ef43fda50b/nes-systests/CMakeLists.txt#L13).

### How to reproduce / Why only now?!

I was able to reproduce the error locally by building with `-DNES_ENABLES_TESTS=0`.

But earlier runs of the nightly pipeline where the issue already exists ran fine, e.g. [the run from two days ago](https://github.com/nebulastream/nebulastream-public/actions/runs/13645140587/job/38142721925). I do not understand, why the error didn't manifest there.
